apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - crds.yaml
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - daemonset.yaml
  - schedule.yaml
  - networkpolicy.yaml
