apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
    name: velero-aws-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:Zw9g42+1d0gLVMfIzq/Jcgg9KfVRkUX2JUsKqQHQWtQHsn+sFv7bbijisG82KdD551vsPRq3+YYE9Pf5EMPGQZorP0mZJu8b9dS4hSn/JizsbHo/JNGYUpORb9sdF9IADrK8X9bosxsgcnwSUyqPWA==,iv:W9ZmUVtfry52YQtWZ3i3PRGFjd8BpP6Z9elwwE0wOck=,tag:dgRZ/jiL6WIQRi2g4Be+lw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcVJNS29zeGxTUmUrT1lG
            bEd6K0JSWG1FSXBaVWRNc1M3b3V6dXlSeDBrCmNjclFBSEFnODFjVStPRW1CTUZ2
            UHZPTjFVRElaeDU2Nmp3aE9nSjZxZ3MKLS0tIDFLcnE4VSs1Vi9lemRUNTJGWlo2
            NlRNTFJRZlJMcWhhN2NTSElsTXU0Um8Kxhn53um47CgXe8ld6msFVNbVIyQ0ruVe
            9x2jfZPnGjeCo+hzwy88IycujLMgQwbz9M1CGepBllze/G/nsu+r+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T00:28:56Z"
    mac: ENC[AES256_GCM,data:G54RoVSAm7xKY0Azah+N3qxYLe+vx/wtRX2NnULFHE7Bmh/scv/+DjOB1OVWyAU8xgfiE4iDhONUhQ9DsaMpfT2sve+k7pNMnP9dn3Z9s0EEqdwV4nwEI0uoZpaKKv7BEur001dpFPFFvQyYMnx+dAihfGRFPEDLTL8s/Sv11SM=,iv:RfFF1X/fHGfb7nzD1s9z7yUThe0M5RYfu8gNaVa45+s=,tag:nV9+sFrSTaHAqAqzY2ewZQ==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.10.2
