apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
    name: velero-aws-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:Zw9g42+1d0gLVMfIzq/Jcgg9KfVRkUX2JUsKqQHQWtQHsn+sFv7bbijisG82KdD551vsPRq3+YYE9Pf5EMPGQZorP0mZJu8b9dS4hSn/JizsbHo/JNGYUpORb9sdF9IADrK8X9bosxsgcnwSUyqPWA==,iv:W9ZmUVtfry52YQtWZ3i3PRGFjd8BpP6Z9elwwE0wOck=,tag:dgRZ/jiL6WIQRi2g4Be+lw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNWhjcVFUb3E1VGpmaU1Z
            VVk2ckpjWlllbzVLQWNhK3UwandvdHVvNDNJCk05dlcxWFZibTAvMTJqQWVWaUQv
            Q1dwM3ZpaDIyd09nWHJLLzdlenhNR00KLS0tIHRuZmRkaHNyemwwbWFyblF0SGFJ
            dEtsVTJ6R0gvUG56Q3ByV0RjV1lRNEkKIDGS29ycy1xILVreymnTgH8Gh7tOuetW
            Rwfa/BcQs+pNqYgyvWZggPhYKVRe79xU4Px6OxIlw3QSYNTjx05PjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T00:28:56Z"
    mac: ENC[AES256_GCM,data:G54RoVSAm7xKY0Azah+N3qxYLe+vx/wtRX2NnULFHE7Bmh/scv/+DjOB1OVWyAU8xgfiE4iDhONUhQ9DsaMpfT2sve+k7pNMnP9dn3Z9s0EEqdwV4nwEI0uoZpaKKv7BEur001dpFPFFvQyYMnx+dAihfGRFPEDLTL8s/Sv11SM=,iv:RfFF1X/fHGfb7nzD1s9z7yUThe0M5RYfu8gNaVa45+s=,tag:nV9+sFrSTaHAqAqzY2ewZQ==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.10.2
