apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
    name: velero-aws-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:Zw9g42+1d0gLVMfIzq/Jcgg9KfVRkUX2JUsKqQHQWtQHsn+sFv7bbijisG82KdD551vsPRq3+YYE9Pf5EMPGQZorP0mZJu8b9dS4hSn/JizsbHo/JNGYUpORb9sdF9IADrK8X9bosxsgcnwSUyqPWA==,iv:W9ZmUVtfry52YQtWZ3i3PRGFjd8BpP6Z9elwwE0wOck=,tag:dgRZ/jiL6WIQRi2g4Be+lw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MTBId2N5V3UyZk1uckFq
            WHRRVERvQ3RoQndQV1hKdDMrb1dtaC9qa21rCjlpUU9GbjltZ0pSMTlmRWsxRzZn
            enhBU2ppUUNJbm1pZTNOczlsbm4vT28KLS0tIHFQL1VGV2g2MVQ3Y0ZtZExHaWcr
            dWk5R0VCZ0xqcEJCZlBGOFRMUDBhUmsK7itInptSWHrgiv9v/bUF+Ibm+qziy5Ki
            bWcH5Va+VfmfM9XTwLwnVCWTLIXtrDTdA540a9FNUEk7l8uVmLQXsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dUp6NTI4WWo0SWN4dkE0
            SUNTWWN0VVkrcnJydnZUUWN5UkkrVjRGL0RZCm9xNWYzVEx5SlR0MGVKNkZMSlp6
            VmYva1RsZmpYd3NIbEtnNXpGTHF0NzgKLS0tIEJxdDlnbWxRRlByc3FmbHRqc1l4
            WkRvT0NJRHlmY1lQWmRoVFpRQkt1ek0KJtRXtfMqo4Kkh39n5Ucv4jh2c0qIfLRE
            2wRuRQ/Z+c0C4B538R6Ht5YlDZRYuqqd4bDgoiYOMUD3lWlYAVyuAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T00:28:56Z"
    mac: ENC[AES256_GCM,data:G54RoVSAm7xKY0Azah+N3qxYLe+vx/wtRX2NnULFHE7Bmh/scv/+DjOB1OVWyAU8xgfiE4iDhONUhQ9DsaMpfT2sve+k7pNMnP9dn3Z9s0EEqdwV4nwEI0uoZpaKKv7BEur001dpFPFFvQyYMnx+dAihfGRFPEDLTL8s/Sv11SM=,iv:RfFF1X/fHGfb7nzD1s9z7yUThe0M5RYfu8gNaVa45+s=,tag:nV9+sFrSTaHAqAqzY2ewZQ==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.10.2
