# Tailscale Authentication Secret
# kubectl create secret generic tailscale-auth \
#   --from-literal=authkey=tskey-auth-XXXXXXXXXXXX-YYYYYYYYYYYYYYYYYYYY \
#   -n loki
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: loki
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:nzHqNH50ksHjqhKMrH3WI59JhMS3Y2mGRj9rKgSowIzoTzbVzbwlImQ31+CIVvX+18J/eJ0NHYwd2TgLd1o=,iv:58HA1pALjXHqPmtGFMOU0EkukrFWfDy3Oqxvfo3SteY=,tag:jifQpvyQvykz6JlfasKMxw==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWXRBMC9haDM0M0VzQytq
            RTlwRWU3cDJXVUZjTFdWcjRyMXdMQXg1SjJNCmU5TUZ0U1l5VnRBMDJqWjBMN3BN
            ajdKNk5CUm5vT3JPS1pGeG5XR3lERG8KLS0tIFRqL0FWcHVaeFpCQnhoaHk4VjVm
            dWE2N0N2RUx5R25yRGFWZVdNc3RiMWsKpHO5bfvoY/ar0eJ1DzaEYMqKVDOUURp4
            4M5dSG4rRsUbrHrM5fEkkOqjkfoHke2NuFpcGZgNDZfAAchPEu2dGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MXNidnNKVmNjUDdMMlRT
            WkVrRkR3eFNOM05jenp0UnRpTXZBaCtXT0ZJCnhrRU8vdzB2eUpuamN1N1d3ZGhJ
            QnoxRm5lakpqQnBMZFkyVGJIdWRFTFkKLS0tIENzek1zU21sV1d0ZHkwdHZYM25x
            QUhxTUpYSUNPUTRVNk5EQkpDT00yZkkKCZiG6mQRIDj2YR/c4FrJQkF4ONbdO92y
            t4MX2fq8gWGyYoAGaDllVR8unzHtXPSx2Ky4dPvSLRpal9CRLfRbMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T23:46:43Z"
    mac: ENC[AES256_GCM,data:8F53P957yVwHti8e5A8vruKFcy+/G0EzAzBH/RfZSliJ87tSALmk/rfJIga/9q8HQIwiL9Op13nzDBSd6JbCZLwi969pP5UhbG8aaLaKQ8rvVJoWLeWnr9VQMVYblNCqgEn1Z25LuI5UCjaxw/vSB0IJjdd72Ki4Yr+sGJ1Yv34=,iv:kXktmOjtpmccIHpRLuxn4FIALwplA5wgfwuFIxSerEg=,tag:vmH3os35VaQmeJttAW4Xfg==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.12.2
