# Tailscale Authentication Secret
# kubectl create secret generic tailscale-auth \
#   --from-literal=authkey=tskey-auth-XXXXXXXXXXXX-YYYYYYYYYYYYYYYYYYYY \
#   -n loki
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: loki
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:QfnCuT/TIhjXHPNgEG67KKUN0J1JVARO/TUAUS1Eaeqr2ZBWD/HigEp03V/5QlrDMrhp4PI3eO/v/izYPy8=,iv:J+QIWZKP0LkY8970/wmyoxPlahKW1+C0DCHVbSC5p/I=,tag:EUdNXjJNbx2QNvOPhqZoug==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSWxVWm5iV29wZnBPNlFK
            clF2OHZqV1JERzlZMlc4dHYrRWcvbFk3dTN3ClNWSEtic3VHZWdDUHlraUNHUlly
            RlA1Q2tDUjVsOFBvTTRLQzNoSUl6V1UKLS0tIFlJWEFQN1J4V3VCQTlzUWd4cEJr
            VCtNTDAwQm1HVkM5b2tvWUpRSHpQcDAKQalKFBmW1fK974MCzoVInR5WW1vby5yw
            exAClC+DyjvJ3d5MHmCc99JwXNCfWEc2+MvOITmga6sShwFkBmrLWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T18:17:38Z"
    mac: ENC[AES256_GCM,data:TDHnsIsTh9VWHuosrOGWkb2CvADs2zfjYKQTcms7Yg4TgZvyyzCJAnQn2oh8i4dwJR7ax97yfKDJaBgwhFGNsAvbOmdQOSN5ZqEXgM9gaBj5EFi7gYE0G8hGxIKy4/01Jb5o2l/4xr+yHlLw8vTMgoWpENTi2JivPFjnzqS43Q4=,iv:U8p1D3hQETLZPThK/eeHIQN5kybXpuhDcYo6QSYxY4c=,tag:zdnZlpjO2Wgxze57LlI2Gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
