apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config
  namespace: falco
data:
  falco.yaml: |
    rules_files:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml

    engine:
      kind: modern_ebpf
      modern_ebpf:
        cpus_for_each_buffer: 2

    json_output: true
    json_include_output_property: true
    log_stderr: true
    log_syslog: false
    log_level: info
    priority: notice

    buffered_outputs: false
    outputs:
      rate: 1
      max_burst: 1000

    syscall_event_drops:
      threshold: 0.1
      actions:
        - log
        - alert
      rate: 0.03333
      max_burst: 10

    stdout_output:
      enabled: true

    metrics:
      enabled: true
      interval: 1h
      output_rule: true
      rules_counters_enabled: true
      resource_utilization_enabled: true
      kernel_event_counters_enabled: true
      libbpf_stats_enabled: true
      convert_memory_to_mb: true
      include_empty_values: false

    webserver:
      enabled: true
      threadiness: 0
      listen_port: 8765
      k8s_healthz_endpoint: /healthz
      ssl_enabled: false
      prometheus_metrics_enabled: true

  falco_rules.local.yaml: |
    # Project-local rule overrides go here.
    # Empty by default; default rule set ships in /etc/falco/falco_rules.yaml.
