apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golink-ingress
  namespace: golink
  labels:
    app: golink
  annotations:
    tailscale.com/proxy-class: "high-bandwidth"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: golink-service
      port:
        number: 8080
  tls:
    - hosts:
        - golink.tail57bf10.ts.net
