apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golink-ingress
  namespace: golink
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: golink.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: golink-service
            port:
              number: 8080
