apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golink

resources:
- namespace.yaml
- secret.yaml
- pvc.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- networkpolicy.yaml
