oauth:
    clientId: ENC[AES256_GCM,data:fxyZ8V6H1IAwuV6YPKYxS2w=,iv:xH4wOAVejnEsWaT8zIVZNum+ZZBZZ1yphN8zwuFrFZc=,tag:2sRfKAiEY/AxwTqXeq9Gkw==,type:str]
    clientSecret: ENC[AES256_GCM,data:FoyEy+74/pmegRberagSUgWXNmi2GHO/hqjAw0etQ5LzjtPfC8x2SMHNhjAc6ExNjQxEI6jJPtz8zh8ubi+H,iv:pA5IwFffTyOp25kSrqo44JBSgcyqkb7cN2CK852KN/U=,tag:LutN4D3dLJO1/BBlaULvbA==,type:str]
operatorConfig:
    defaultTags:
        - ENC[AES256_GCM,data:QGW/LXpr2pZEpp8MApOtjQ==,iv:x58egodXchrEoZheE7ovCofxUwenZbvn0wc/3XBxYBA=,tag:xpjnS2EMiKesEYz7QRonsw==,type:str]
proxyConfig:
    defaultTags: ENC[AES256_GCM,data:GqmGQMuPwC9wcWQc0KEYKg==,iv:0nzvErlYmT3G67uE40j9SSjmkbIjb+64LcgZgDB+dQ8=,tag:eZnkYkXMLxhrEIwlvgVAiA==,type:str]
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdkc0RERlRnZPZTd3MEVL
            dXRNM2cyaUhjZVBSQW1sY21iSzhtNnFFVkVVCjBNc1k3OE5nQW14SzdqRUZIM1Y3
            M3Zhc1RISHZxZlRaUHcrVWd5RWRFcUUKLS0tIFp2a3NiZ010bTNHUG16NUZTbnJx
            a2xrZ2w2bk94UG9oSm5Xc21ZQnhnbncKPhOgq8wDOr31V963Ir4U8kT6W6/EfAxx
            wIRJRlRVLISKAA7NM2OXBczPYUtuYWDhT3DYmGZUTk4ys9yWCsTetw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T19:43:33Z"
    mac: ENC[AES256_GCM,data:LiCIVnpw3AbAl6zK4bzcM6jfUq6bLUm1/ExabIB9WT+0CpIeHgxXMldV8goNoJl6OK3LLFDh54uhEHu7HBrSdFZlzJW04RZd/VzvctuZMWNtviqGO9kEZzY+pQ63pR6vi/Xr3e0bXwxo+gOy1u7szwBSqJ0XkK7C52qgfNbOCLE=,iv:rUpmt64ilgFFcOxfw6m+Q8gwQLY33EGpC7btMVgMWo0=,tag:ZKErtmg1nlCVNUHzW/c41A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
