# Tailscale Authentication Secret
# kubectl create secret generic tailscale-auth \
#   --from-literal=authkey=tskey-auth-XXXXXXXXXXXX-YYYYYYYYYYYYYYYYYYYY \
#   -n prometheus
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: prometheus
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:J+nhoS7OizXp+32dq1ADmVFEL3NDGlzZro2BWrW2Yozj764rFBG+JCNZ8IgxasxL7xEiol4FoktB6JQkx1I=,iv:pIzfTsqCQmWD5XG1pz3mkRUqivyxHc1hgBSOU/Md3uI=,tag:fYVTUIukh9l0DeFKBKdQKg==,type:str]
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMDlhWU5md081SE00RXlU
            dm01WGgrUGYwNmJvZml3UEw1YnI3Mi9rRlJvCjlINU41OWhubUIwSk1DQTZJWXds
            VHBxK3c4cTNOanRPajcvejBKcHcwb2cKLS0tIE9zTS8vcjgzS2xGN2tlWVZCWWpF
            MXdJNm1TQjJlRW1ObGFJQ1gxMDNCblUKRBc1GyNqIk4gZRfwgUkMMfwMCRYyL42o
            yLe8FAkbYkFpzNTzMHQTab+cFRwLxyX4GX4B7Ic12LgGGjnwnnV3NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T23:46:43Z"
    mac: ENC[AES256_GCM,data:kM46WEW5lnm221nny6v9f0oCCYOB+a/bSt92ozwx/Div6QNKgsRAe7X58Suo85MNn5GYyfEP5vFd9x61HhOtIw9qjrwR/KHn/Xhuc/vNna47kdDSs3lRO/S+pkcu5op0TAhAZfQAN0ShoiRdvwbmfXK5insO1RrQBam8w8dJD+0=,iv:BtQ1IGLfbQ4W4qoMbQv36duM34Cq+pZSQsYUnYUZWak=,tag:DZs9si762r9sl0G/Dq2P1A==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.12.2
