# Tailscale Authentication Secret
# kubectl create secret generic tailscale-auth \
#   --from-literal=authkey=tskey-auth-XXXXXXXXXXXX-YYYYYYYYYYYYYYYYYYYY \
#   -n prometheus
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: prometheus
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:J+nhoS7OizXp+32dq1ADmVFEL3NDGlzZro2BWrW2Yozj764rFBG+JCNZ8IgxasxL7xEiol4FoktB6JQkx1I=,iv:pIzfTsqCQmWD5XG1pz3mkRUqivyxHc1hgBSOU/Md3uI=,tag:fYVTUIukh9l0DeFKBKdQKg==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OWxKczJsQm9xd1RpcklX
            Y0pUeExYeTlNd2tVYnE3K3dicnBxWldKdlNnCnVjRmhtU0c4ZWZUVVAybnY2QnQ0
            VVF3enNtemU3djlTc3AwemNXd25WQUEKLS0tIEwwSDAzQmFVeEJ4eSsvTGhDRzdm
            SWxqeUFwQktIckV5ek1NTFdIV2dhdzQK0slDixFdW0kbiNaaLXiZU7RNnFXNFtr5
            f2d66o3uY0QfuT7Qk02uy2h6NIJdb3je2PQL4JTe5ovPDCEj/ztJEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T23:46:43Z"
    mac: ENC[AES256_GCM,data:kM46WEW5lnm221nny6v9f0oCCYOB+a/bSt92ozwx/Div6QNKgsRAe7X58Suo85MNn5GYyfEP5vFd9x61HhOtIw9qjrwR/KHn/Xhuc/vNna47kdDSs3lRO/S+pkcu5op0TAhAZfQAN0ShoiRdvwbmfXK5insO1RrQBam8w8dJD+0=,iv:BtQ1IGLfbQ4W4qoMbQv36duM34Cq+pZSQsYUnYUZWak=,tag:DZs9si762r9sl0G/Dq2P1A==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.12.2
