# Tailscale Authentication Secret
# kubectl create secret generic tailscale-auth \
#   --from-literal=authkey=tskey-auth-XXXXXXXXXXXX-YYYYYYYYYYYYYYYYYYYY \
#   -n prometheus
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: prometheus
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:oAnZgGcnZvzYhnwqFDTI7icXoztR7W3DYqYeC3+Qixkjb6x2w9MM9YHFRdUmMJg6CzAE7Aya4xLFY0446pM=,iv:XK3FDkkjIPQlhJgmfjUJDjCEo1/KA3nbwkAmB3m4Nw8=,tag:0g7H1uvp1GSK9fqSlom6ww==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSis3S1RDV0N2aEhkQWNG
            Ynk1NzYrUXhMRndUN0h4Z2lSQTlYMW1zaWxrCkF2bzZNVlR1VG8wY2ZlUTNDdXo4
            SmFpNjU1QjZyalJRN1JSakFmVVJjQ0EKLS0tIFgrOHBlTElTTDRTOERpazd5blVD
            bUpUSSt2QStaczE3K0FQZ0pxa3ZJbFUKKH293BPUqboP7qxffPyKfBBuR5AJQUwD
            RehcXTyhcBjMeGx+i0po5mTlX3JNPqEqsCH83v6MYIrBFY8M9GZ2rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T18:17:39Z"
    mac: ENC[AES256_GCM,data:qlQteK1p1gn4NJIdwbDjao5aoe9nq0QLq3bA3f5vpo6QNo5ugL9skkvdz9cgq4CKRmv/2v1cE3xoIqnZd4JPHFEH+dQjPMlgtqhZ+7PF+kJdpa6kI8CP74hxC8CBlEGnvtTEUmBp500ZW7HgO5SKqWGQLXJim73A4EoaUN+fA/M=,iv:pw0oGYw6OOPAqW39pwzEZqpSbsyTmW10tUTWsUvUqUA=,tag:RMMRefc+LkFXkJnUUlkPwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
