apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      # Módulo 1: Ping Simples (ICMP)
      icmp:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: "ip4"
      
      # Módulo 2: Teste de Internet (DNS Google)
      dns_google:
        prober: dns
        dns:
          transport_protocol: "udp"
          preferred_ip_protocol: "ip4"
          query_name: "google.com"
          query_type: "A"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      # --- O TRUQUE DE MESTRE ---
      # Obriga a rodar na Oracle (Control Plane) para não gastar RAM do Rasp
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      # --------------------------
      containers:
        - name: blackbox-exporter
          image: quay.io/prometheus/blackbox-exporter:v0.24.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          args:
            - "--config.file=/etc/blackbox_exporter/blackbox.yml"
          ports:
            - containerPort: 9115
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9115
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: 9115
          resources:
            limits:
              memory: 50Mi
              cpu: 100m
            requests:
              memory: 10Mi
              cpu: 10m
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox_exporter
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  selector:
    app: blackbox-exporter
  ports:
    - port: 9115
      targetPort: 9115
