github_runner_pat: ENC[AES256_GCM,data:jfVxpXI5FPRIvzoRGsb589jIAaokr4MHO0E0bcFL31xmKwOvmqSzvA==,iv:LCLKUqT3lTv6pwklpYw0VjyNTdFZll+452Ryfasuo6s=,tag:+fzeAPmne+Rd5KujDVV0+w==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdUdLQXhmc0wxS1N1RWh3
            OGp5TTJ5OUlST1d3RkFHc3NFZmZXeUlHZ25JCm9rT0VrSzZXOHYzQXB4bjIrSHNF
            YU1DVzRkQ29TWW9ORVVWUVk5R1RxRUkKLS0tIGVGQ1RKc0UxOFNrTWhSV2lFcXpF
            bSt1cHFrby9mSnphUXZPSzZOb01CVHcK9pbPNwwOmyCO6WO0F/HkgY7ZgrvAZjCA
            DPsVHAqS4WrJXWVyJ4d+7Xqx+dtKRms/V6YHMFj6TnIWJlKSXaz2vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T16:18:29Z"
    mac: ENC[AES256_GCM,data:J+GYQu3XDUX6itECUkQD7cWMYNqk3QTllVo2ZcANcgAufSkcrmuYi8Lb36MeSOcbgc4ow1vnHifzCOntoLoUmWz/oJPdKedRTeT5ELt6FtfF+MowiDHbNsXgkIK5BPNZR3lY9xRenbDRIHy+UAlbCeCOP+8iB3DSQ8gAUOyXfOE=,iv:f4v74c8+v5LYzietwBINxfmmBln1kgxTti08HYEgULc=,tag:aeDcThcEgjFOBoN21mzkxw==,type:str]
    encrypted_regex: ^(github_runner_pat)$
    version: 3.10.2
