github_runner_pat: ENC[AES256_GCM,data:hcg4o0iAwRdb2eownm6l2kXqPd77fja+rbsKiY3jv/t+UBEg9Lesog==,iv:TeM0eCWM0QztV7axATpM7Y4OZvJDAKN6OJYnCBuhznY=,tag:0w/ENI89ogvXOP8/cM488g==,type:str]
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNmlIcS9vN0FtQzRQdjR2
            Y2JmQTE0RkR4T3VHT0NzSkloWjVVdEYxWkZFCjFoRys3TVVqS1lZcSthUTNKcjBW
            NCt4UDZNUlhUc2pKUTJTM2VLblZjc2MKLS0tIEhmTGVQSTVsNEE3Q25GR0Vqb0pD
            VE1lNVFsVGcxT2xuY2lPQWNoY0xoMU0K9Qicp7AW1IIdefAoxnLgjFEzJIzx1Xa2
            WpsaJsu90NYNLhrB4pdnkHQVS7lwQ2eyApIZjbaeBYgvBVSuiwZClw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T19:24:30Z"
    mac: ENC[AES256_GCM,data:pOq70s9XQ6wh1N5XrpQp2AqAwYhPgYAH6h54mWdkgaoZIYNQNTUGk41LNTbqRzfsQslPh6t+FzBCA1KwxLH3BECxBMkH/KqStCGSR4qbRJDb62EAPvSgJMx1yK54EwNNCuprmLWQqR8OOwH93PNm3abR+JbHmUlJM4AGNELKpUk=,iv:ReSNyrKI7iUyTRctSh4WMOiqw6cbHTs5Yr8mClFfDl4=,tag:ib62x+3L3zg4odWetELxRw==,type:str]
    encrypted_regex: ^(github_runner_pat)$
    version: 3.10.2
