# SOPS-encrypted vars for k3s_server group.
# Decrypted at runtime by community.sops.sops vars plugin (see ansible.cfg).
#
# argocd_extra_* keys are encrypted (see .sops.yaml creation_rule).
# These describe an OPTIONAL second ArgoCD Application sourced from a private
# repository. Leave keys unset (or remove this file) if you don't run the
# private side; the role will skip extra wiring when argocd_extra_repo_url is
# undefined.
argocd_extra_repo_url: ENC[AES256_GCM,data:YAksf40lrx/GuYUTlpzMVEE3sLhREsvltecagCGNGr8JlhFQuMdmgyQqlfQZbBCrlc5D,iv:GOZZCAm2BXOkgByfDDGZ9Sat+dvuWA2dPXiqpGoGwRY=,tag:OpruEogp2ydPonIePS67PQ==,type:str]
argocd_extra_branch: ENC[AES256_GCM,data:BWYVcw==,iv:zAJkmCPaVEhm99rMXOoOXHC2W1NVEH6m6iVT1hAjGro=,tag:my0cqYz7289Mgs7iCIj0cA==,type:str]
argocd_extra_path: ENC[AES256_GCM,data:toIta9AtFHk=,iv:hZt+dMHVDzCRhIgQxStKQvBu22Do8q3LEA9Ws+atLU8=,tag:DgaYVTDzbVfbIbXSWZiaSA==,type:str]
argocd_extra_app_name: ENC[AES256_GCM,data:kBOXTmZBxh5d1kRFo1vvkUtw,iv:fiZFvWGzfOiqOVRsXk1asz4UaaFf+CSAG5aofhJgBog=,tag:btC4wwCnL/d7m+q9E1f8ng==,type:str]
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMGtXcE9NNmxkN3NpRzYx
            eFJVRjUramtoZ1djNG03VnZ1Z2ZiMUFRNDNvCmI3Y040OTYzanBxemtjZWJFdERv
            L21zNFY2Vm8ydHYrTzhHc0ZoRUxzZFEKLS0tIGtNQWlaSHdTZ1lhVzJNaHdyNVU1
            Qkg3SjBqVUhSTlhDOUs5NjdyQkZTSm8KFzVIHwjZoukNzdXnP8Eud327c1IwgLGv
            hKZSTExFrIwSuHnx4kLrORZrml3F7yxyjNHDAVvJGWokT5seYlSHnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T19:43:33Z"
    mac: ENC[AES256_GCM,data:4dK6b8QSXo8X8r7A8ksRZ6A01k/uB/c38Aac+WdD9q3cgiozmN/Dn89GuF/okX+dSAf/UzBjelLQMmqaQk+xGw8Pk1yNyFA+Kham+HJewOkvAv9EuOXNt3JGwyb5SVHMpvDf77owMNv2sYwfBAanSCCXg2T/dQD5YQCAnLxmLLs=,iv:Lu1RwPuwiprvML3EmSmL0M9JwqYR++Q2UhqHBXYof4c=,tag:fKJiObjF18RfJ+Tn7QIe4g==,type:str]
    encrypted_regex: ^(argocd_extra_.*)$
    version: 3.12.2
