apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-local-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-adguard
  local:
    path: /mnt/ssd/k3s-storage/adguard
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rasp-pi-03
