apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc
  namespace: adguard
  labels:
    app: adguardhome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-adguard
  resources:
    requests:
      storage: 5Gi
