# Tailscale Authentication Secret
# kubectl create secret generic tailscale-auth \
#   --from-literal=authkey=tskey-auth-XXXXXXXXXXXX-YYYYYYYYYYYYYYYYYYYY \
#   -n adguard
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: adguard
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:lZRH6dis4WsCmCSqyl5+kjNFtssmvMX97Gau8Mck47Lv73H5tfLAliNF8UAYS+ET+OX7tTN21Jbv/V1z2s4=,iv:6LKxc2zi6krftlC3g39V7eiBgdsmDZXqXW/oefE5VA4=,tag:3gJ8JmgOHO3lQSBSVkfhrg==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRXBvbWFLYUZIUTRiN3JL
            U1d6QSt6R0RRK1RoYzNFaWRPd2RZSWxrOWd3CjFNUlA2SzhlZ25CMWE5Wm9GZ0gy
            RXVuem1FUnlQZFRDK2Y4Qyt2clhLdm8KLS0tIEg1REhRcUV4NUJtYStQMkRRM1lt
            ekJiRXErcEtYRTd4eUdtbFVyTitwMjgK1hNQMRw8rpzHBogLkYoQOtRVjDfoGSRL
            mQxiLsVWMTVRCRRWpz/aAYtEV2sv0dUIzpqZJTpLMXjm5Gfoue9oAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T23:46:43Z"
    mac: ENC[AES256_GCM,data:0UGNbJLt7eU20dY/9nfP8Tr1WrQJlDi2nxpzio0H7UuRwFk+8GbXmMdF34toW4Eayfo0MdG2KemKOu79J+OqUQJcXl/7MaK0kYFLaoM5E6n16H8jcU+SXr2rT3aRXI+WuXuDvgyg45Uhoqb/2KBHsMoa8BRxFj378OvSc2+xD2k=,iv:/VimVk+vMU2MkbwH5xIk+oTowIg9COf+AcsP+6VEIfE=,tag:fqa0iJKrD+Grafo0MaF4TQ==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.12.2
