# Tailscale Authentication Secret
# kubectl create secret generic tailscale-auth \
#   --from-literal=authkey=tskey-auth-XXXXXXXXXXXX-YYYYYYYYYYYYYYYYYYYY \
#   -n adguard
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: adguard
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:lZRH6dis4WsCmCSqyl5+kjNFtssmvMX97Gau8Mck47Lv73H5tfLAliNF8UAYS+ET+OX7tTN21Jbv/V1z2s4=,iv:6LKxc2zi6krftlC3g39V7eiBgdsmDZXqXW/oefE5VA4=,tag:3gJ8JmgOHO3lQSBSVkfhrg==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYW9KbHEzZWtrdms0TU1j
            a051aXd6UHBmL0pRL1dlS0VvRmZuQ2d0WGxJCnZTYVBsSjI2MCtOZC9XaXRUd2Yr
            ek5QRm9xQkMxRVh0bElUZjg3eEFyTjgKLS0tIE9hclZVMExOdHhJM3RuMFRNMnlv
            TGVqbjUxVmRzNi9KT0lRdHZpbzUvR1EK4tfWxeq8Yz/9hdViMgCoD4UcE1UjjFsY
            N6Y0zipcovzRES5BDy5wczACsXhuetbv0qzjLGg7QlrrzIxp47hKyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNWFLbGJ4SzQ3UngvSTc4
            MnRQU05jYVJPT1o0cnV0aGxkQklYUGpYczBBCjFuaXEvaFdQMHE3bUoycURFRmFy
            MmVUVGNFL1VYemg5UjdCWW5CZEtSNFkKLS0tIEVrYy9YUnJEZUl4dWRoWEdNT0tN
            U3lFMVU3YTJqQmVZQTdvOFh2Zkg3WTQKZiE7Wzu3l7MNe34O7K2O83dJfPoNS886
            +JUtWJ06GBZAzHxGkQyYx3Hoknw+JAd4S2s91FbaDBRoj0Vw0K6G0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T23:46:43Z"
    mac: ENC[AES256_GCM,data:0UGNbJLt7eU20dY/9nfP8Tr1WrQJlDi2nxpzio0H7UuRwFk+8GbXmMdF34toW4Eayfo0MdG2KemKOu79J+OqUQJcXl/7MaK0kYFLaoM5E6n16H8jcU+SXr2rT3aRXI+WuXuDvgyg45Uhoqb/2KBHsMoa8BRxFj378OvSc2+xD2k=,iv:/VimVk+vMU2MkbwH5xIk+oTowIg9COf+AcsP+6VEIfE=,tag:fqa0iJKrD+Grafo0MaF4TQ==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.12.2
