apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unifi

resources:
- namespace.yaml
- pvc.yaml
- secret.yaml
- configmap.yaml
- service-mongo.yaml
- deployment-mongo.yaml
- deployment-unifi.yaml
