apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-mongo-pvc
  namespace: unifi
  labels:
    app: unifi-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-pvc
  namespace: unifi
  labels:
    app: unifi-network-application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
