apiVersion: v1
kind: Secret
metadata:
    name: unifi-credentials
    namespace: unifi
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:S0dlZw==,iv:UMhsKWMx+GB4hIogCnk+7ktIugozu8QlC6vjsKDXaUE=,tag:nHYacx7PuEjuEsUkXhoLvw==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:Oa7OwwoaDgkbjiX7LNxdXduQGIIqdQkl8cJ40F7KSL8=,iv:kepel67iL7vb5oMeCryHSTRuUHE5zV1f9Ns3Za3IFOI=,tag:yA13PBoBoFo7SLRt+dFp2w==,type:str]
    MONGO_USER: ENC[AES256_GCM,data:fS25734=,iv:G3mEGd0v7/TUc/9pcd+PwGVzJJdy+lcfLT7fHStQ0D4=,tag:TIq/3woa62nKL2SpDoFIjw==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:zO7HrEz9gOOHqHbHaOcXa/GRz0b3t+yscJ0CZeblmPs=,iv:ATTLz7vztBn9OgPASkm/IcXtZcEzW6DayRNIsPZsvG8=,tag:tA8S23EcipdJyG3woSwzZg==,type:str]
    MONGO_DBNAME: ENC[AES256_GCM,data:Q/iZ4Co=,iv:rCWoRq85C7MmQ1rdUM9c0v9PxFKrpBDj4C+b41RBNGw=,tag:abbw0YarWwwBMHECS+wA6w==,type:str]
    MONGO_AUTHSOURCE: ENC[AES256_GCM,data:OX7FjuE=,iv:XHieeqTFrJTwmC6zEZDDQ1Yam5WOdmZF23eNyu9vJMI=,tag:MVBG31Z8E3GCaT2xngMy4A==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTTJZWW1GK0tGMDR6bHc2
            NEJVYUlnM1dxSHFZaVdqd3FJUk40ekt3S213CjdtUldFSUZqWjUydW04Z1JZcHdR
            WXlCZ0VpaVlpYkVMazhMak9ZWjhXOGsKLS0tIHpPc05VUThhdXpOemJsL1J5M295
            czd0RDMyL2gvQ29yWmxlZHlPMzNwaW8KuS/70KtdOYULs1QwX3xteRbXimhcyJtd
            GrQJjXfN/jdpuzIwRMsczKDkSimAfi/w9ZCCIbweBAk3HWBzLfFtIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ3hkT1JTTVQ0MHFoMTJB
            clNSNEZHcVVDZGFQT1R0MXh5eUd2dW94STBFCk13MjFZanNDVDRGbnhrNVlUamRo
            U2ZwdzdlMWJ3a2I3eStFM09QM3d2OUEKLS0tIDFZZjk4RWoxTUNPR0lXV1pMZUdU
            OVZzUVpmSE1RUmRCenhrSDhra25zU1UKre9VXv5QGbT5aldpO8xJEKm11B9wbtWV
            z8lOPFJRQ9TNtA/6Tr/5gd4iIsySggVBRAzbX3cbFuxjZN4B8y2bHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T12:34:41Z"
    mac: ENC[AES256_GCM,data:kJzYZWDFk8coM6IFvVMN/eYdDhYkRd7E74X+VVKvqvfF6yYAk8kzHz7PK491Gy0ZhXbK+/jGtcq7lO+eowLMOJMF26IZlSQNQuAb1wHzJ45/vDBnAq+iEOClG14nNjGyyKZJ5AV055ed2O1VMeRzcKNm7dlt16S2ahcM6bQ/XpA=,iv:/jHQtcMwMhf0EiNzqd73eAtgX7TZZl+RUNwcRMxklW4=,tag:BAkySGSVMTlF+wMy5VKHUA==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.12.2
