# /infra/aws-backend/main.tf
#
# This Terraform configuration creates the secure remote backend for our main
# infrastructure state. It should be applied once and then rarely touched.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.45"
    }
  }

  # This backend configuration is local, as it creates its own backend.
  backend "local" {
    path = "terraform.tfstate"
  }
}

provider "aws" {
  region = "us-east-1"
}

# Static suffix so re-bootstrapping (after a full AWS teardown) reproduces
# the same bucket name and the dozen places in infra/aws + k8s/apps/velero
# that hardcode `homelab-{terraform-state,velero-backups}-kkuhocyv` stay
# valid. The original `kkuhocyv` was generated by a `random_string` resource
# in this file when the homelab was first bootstrapped; once the suffix
# was baked into downstream configs (backend "s3" block, velero ConfigMap,
# var defaults), it stopped being random in practice. Making that explicit
# here removes the destroy/recreate trap.
locals {
  bucket_suffix = "kkuhocyv"
}

# Create a private S3 bucket to store the Terraform state.
# tfsec:ignore:aws-s3-enable-bucket-logging
resource "aws_s3_bucket" "terraform_state" {
  bucket = "homelab-terraform-state-${local.bucket_suffix}"

  # Prevent accidental deletion of the state bucket.
  lifecycle {
    prevent_destroy = true
  }

  tags = {
    Name    = "Homelab Terraform State"
    Project = "Lab-DevOps-Pro"
  }
}

# Enable server-side encryption by default for all objects in the bucket.
# tfsec:ignore:aws-s3-encryption-customer-key
resource "aws_s3_bucket_server_side_encryption_configuration" "state_encryption" {
  bucket = aws_s3_bucket.terraform_state.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Enable versioning to keep a history of the state file.
resource "aws_s3_bucket_versioning" "state_versioning" {
  bucket = aws_s3_bucket.terraform_state.id
  versioning_configuration {
    status = "Enabled"
  }
}

# Block all public access to the state bucket.
resource "aws_s3_bucket_public_access_block" "state_public_access" {
  bucket                  = aws_s3_bucket.terraform_state.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Create a DynamoDB table for state locking.
# Customer-managed KMS key (aws-dynamodb-table-customer-key) intentionally
# skipped — AWS-owned key suffices for a lock table that holds no secrets,
# and CMK adds rotation/cost burden without commensurate value.
# tfsec:ignore:aws-dynamodb-table-customer-key
resource "aws_dynamodb_table" "terraform_state_lock" {
  name         = "homelab-terraform-state-lock"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }

  point_in_time_recovery {
    enabled = true
  }

  server_side_encryption {
    enabled = true
  }

  tags = {
    Name    = "Homelab Terraform State Lock"
    Project = "Lab-DevOps-Pro"
  }
}

output "s3_bucket_name" {
  description = "The name of the S3 bucket for Terraform state."
  value       = aws_s3_bucket.terraform_state.bucket
}

output "dynamodb_table_name" {
  description = "The name of the DynamoDB table for state locking."
  value       = aws_dynamodb_table.terraform_state_lock.name
}
