# ==============================================================================
# SOPS-Encrypted Terraform Variables for AWS Homelab
# ==============================================================================
# SSH Public Key (will be encrypted by SOPS)
ssh_public_key: ENC[AES256_GCM,data:5ZcWJRkAddZ6zpOvy/z45CY7qbEh39pen3G9+0g1VESaWIZ/NyViQhR7qQTTPzMhIZoUZ2IuemJhU63Dpctbp7QAO1wjDZs0dOvVUWplfxI=,iv:xRs/M7HWA6I+Z5N2szL/7cjEoyJMCIo3klu/UseVZNY=,tag:A4YYqWvxgpFTpPo/TKrbqA==,type:str]
# k3s Cluster Token (will be encrypted by SOPS)
k3s_token: ENC[AES256_GCM,data:aCcBoPb1QD9eQgcphjCMZOz2EBIdf68Kx7bb2TIm5eAcGb8yimNN+7hfky4=,iv:oI1cEaQLSV3AF5oLaj0LHuhrVig63oFyi0zaYC5/Rl0=,tag:QKfsn6ZyE4+naTZ3pbZenA==,type:str]
# Tailscale Auth Key (Zero Trust mesh network)
tailscale_auth_key: ENC[AES256_GCM,data:mfcOK5FY2TNuIGU9yb49ij9x6hkWeRqHeZ0itFvgYhx9RluKHBwXUW+W6hAxW66rJMOcXLGZK/dLr+/8W3Y=,iv:552+X3CV3y+3NQpM+FQ/DUDsdJtAj3XXlABsE2PkT3k=,tag:qQn9dsTU08zh9w3azNdtZA==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QXgrNi9sZUtieU9JNFRB
            WHRQZGcxakJMS0dyMzd5WUJRZnV3S2hOd1M4CnZGcmdVUDg4cy9KUFdqZE1ydXlI
            L2ZEWDIxaTgrTHlJUytoUTJsSktJNEEKLS0tIElGbWlWUExUajVNajlmNHpZWUdv
            d09OSWFwQS9ENVEweEJLeGkrYnNUUVEKEQU+Fr7rIkapPd8vrWWZ9GFo4adTbxij
            q1fSdQdxxc9ogqzko9hZt/N4VLS90vgXxWAqzzjpTiF5bOd8np9s+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T16:07:02Z"
    mac: ENC[AES256_GCM,data:Pvn78kVuWTNb4XGkSYAOtFeGgE5L8gMRI7eHjKaEmzMljB7mUL4qhgsg0VMEHJQcyBc/xoca42s+yrQA3gHJa7JtQT/pZAhr4/qwcvEL4yZ27qSajaIt+eFIMrTKXMIHF8NY/vzJU13yDaHMEHZgHTrHiDOfh1yL/2u2yzMeT7I=,iv:BLccFgM5ANta82N6pIkNfwijeh9YuTX06MUFIxSgibU=,tag:9YDi5g1VTxHPOutd5QqtMg==,type:str]
    encrypted_regex: ^(ssh_public_key|k3s_token|tailscale_auth_key)$
    version: 3.11.0
