apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
    name: k3s-snapshot-aws-credentials
    namespace: k3s-snapshot
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:evq/4UtX3JDJiDdEr4I7kygjbmg6Rl+jlDisJ09/ltKk6tZKUiDT374+OElOXnE3S+bEtpj2HTKqIekMjaeFuiMf9ApTAR4LZNPIAEPmIC0GWYZ9uc0rOibXDOFq8KuuXTlCeTNNPYmzP+rmz6AqzZbpmRX/NqTzcYvu+tm6gt/JmUbe4yyRn4oNV+gLETgkEMRo19KQxg+IYboi,iv:rwTxC5dtQEmonF9ZTWzAl2SIkZUgzb2JAFOtcuJvpwc=,tag:cA+2QNlKuGe+iuJDF8yz8g==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ0dNK1VRaUN5cTBuWlNk
            WHQ3M3diaW5MdmNwQ2dMdlJ2N3lKVHgrQW4wCm16QndaWmVlSmxCTThZQkJnUEwr
            YlZDRlR2alZPK2cvM2hpS3NhbE1FdzQKLS0tIHl0d2NEOS9lRDlhc3pLL3BFSXN1
            UUgwczR6UGR4ZkYzcUtCMnVNMWRubTAKLWAZXppEDrFTPKi49h6Lw2OOgPqXIjY2
            erjbYP0bTWsycp+K2Ut19Y8arulzPoGgK0YylciBAVrhoeTWJCWIfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T17:16:57Z"
    mac: ENC[AES256_GCM,data:VUGrK6qGcLKPchy+/q7R4Jok9/xrGwlgpoMbL5LvvK5vVBJtcJUGUZux4CI620UEljgkZQKeqcPKQCryg1FSVuXkzPVNE96D1fiULNEzD2CxYTiMfCkyb1WhXJtMsZMPkFWrbuTuchnL4hRyP0VmDJfgg7Hjz6XQ908xso8KjkA=,iv:cc1WWJPSd5gga4f0ZoeV+GEGdsW0aCMOA7I3q3e/Ru8=,tag:v2pz3V51GsAp1MS+Y6E57g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
