apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
    name: k3s-snapshot-aws-credentials
    namespace: k3s-snapshot
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:evq/4UtX3JDJiDdEr4I7kygjbmg6Rl+jlDisJ09/ltKk6tZKUiDT374+OElOXnE3S+bEtpj2HTKqIekMjaeFuiMf9ApTAR4LZNPIAEPmIC0GWYZ9uc0rOibXDOFq8KuuXTlCeTNNPYmzP+rmz6AqzZbpmRX/NqTzcYvu+tm6gt/JmUbe4yyRn4oNV+gLETgkEMRo19KQxg+IYboi,iv:rwTxC5dtQEmonF9ZTWzAl2SIkZUgzb2JAFOtcuJvpwc=,tag:cA+2QNlKuGe+iuJDF8yz8g==,type:str]
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SUJ4YU8wTVVwQ25xU0NE
            UDE5UmlPLzlrVk4vbmRjdkVLYm5iM0kxY3dNCjI4TDJjMGxMZzNuMWY4ZFpyVGhB
            NmxoeUtXbW85UjE5NXV2dm9za3d3eW8KLS0tIHZaaTF4RnBzb0pQcVFLSDM3N2tR
            VHAwK214dzNhRktVSFJ4Ry9GSHlkOGsKypuL69QYxYUSKgKrpFTppL4BZy31lXDU
            PJSsLUVvkccEqxev1tJVP5Wpn7EyLykbsH8sSWhImDowyFVSdTZbiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T17:16:57Z"
    mac: ENC[AES256_GCM,data:VUGrK6qGcLKPchy+/q7R4Jok9/xrGwlgpoMbL5LvvK5vVBJtcJUGUZux4CI620UEljgkZQKeqcPKQCryg1FSVuXkzPVNE96D1fiULNEzD2CxYTiMfCkyb1WhXJtMsZMPkFWrbuTuchnL4hRyP0VmDJfgg7Hjz6XQ908xso8KjkA=,iv:cc1WWJPSd5gga4f0ZoeV+GEGdsW0aCMOA7I3q3e/Ru8=,tag:v2pz3V51GsAp1MS+Y6E57g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
