apiVersion: v1
kind: Secret
metadata:
    name: lifeops-jd-db
type: Opaque
stringData:
    db-name: ENC[AES256_GCM,data:qpb1Iqdfrg==,iv:T9+C5BNil14GfDMvHwvOIJFZxHH6h+NFE7ADTLe1itw=,tag:aJzinoZfecYx2Xhi9XFgHg==,type:str]
    username: ENC[AES256_GCM,data:JdVn4ojg6g==,iv:PehJxcVksQWBXs8cJr16BDIX+A726jXELhvBmWHGiys=,tag:YMJtJI3R7yMpwTUeNLSTwQ==,type:str]
    password: ENC[AES256_GCM,data:XYfuMnoje3zsfTgN0tXKv9I6zMzxdUCsyHBa/VIV72R4qY0pKU7ctqkJ6IN6uFk=,iv:8Z9molWQ3t1s4P5te0QRqh4dg/Jw1FXqtYqoENqaJyg=,tag:GLWZUfD0mKc3HXF7UC3YMg==,type:str]
    jdbc-url: ENC[AES256_GCM,data:6oS2Z4/WaAWAtUnvuZfCHe8IdL0G7AyT1CU0ZJfEez4L5JebsD2lZZFAiCM=,iv:6HI9SxKjcB+JlEs8bnrapD1Zcp/yvZlImFNGqOa/+U8=,tag:x2ikweccZn5/tFa1QRg1OQ==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYlBMaDU3T1c1Nm9yaXFZ
            UlRvTGpYQUd4d0x6MklxR0RseEI3OWluY21jCk15N3JHWGV4bnhpQXdLaTlodXM4
            a3NGS1NmRWJUVXVtckRaRjhpZXBuTFkKLS0tIGdJYVZaK1JSN0lyLzI1ZndyQXc1
            cE1YK2d6MjNpUUpiZ0JpNGtNREhqRFUKHKEZDdxj+rA4L54L9jY+O3lwHj8MpuHg
            nAuKbv1JdaVI0LwirUjjEC0BioA3N7sY0MjI6A9aPrZnYbUSnoa9gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T20:30:10Z"
    mac: ENC[AES256_GCM,data:PwabRvCY2aDCoHD1YyfZR9WqMigP7a9ppSIHqAFNpJdwLQ2U9oArt5LuT2XfgMJPz9pXC/b+61BxNUoMdcOfhRHLqExl1vexC0MAkd6xW0oSM2mBUsmykcZYDo0jY7+TryrBz7sO8wG3XbQoRVEOTtMHlTJl3X5EFCMGuRABeMA=,iv:iDU/s0qzAhUg7MZtDYZ1jDfFVTse5gJHMqX/LYhDZaA=,tag:aTDAMEd2oKoIt+jSE7lGKw==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.10.2
