apiVersion: v1
kind: Secret
metadata:
    name: lifeops-jd-db
type: Opaque
stringData:
    db-name: ENC[AES256_GCM,data:qpb1Iqdfrg==,iv:T9+C5BNil14GfDMvHwvOIJFZxHH6h+NFE7ADTLe1itw=,tag:aJzinoZfecYx2Xhi9XFgHg==,type:str]
    username: ENC[AES256_GCM,data:JdVn4ojg6g==,iv:PehJxcVksQWBXs8cJr16BDIX+A726jXELhvBmWHGiys=,tag:YMJtJI3R7yMpwTUeNLSTwQ==,type:str]
    password: ENC[AES256_GCM,data:XYfuMnoje3zsfTgN0tXKv9I6zMzxdUCsyHBa/VIV72R4qY0pKU7ctqkJ6IN6uFk=,iv:8Z9molWQ3t1s4P5te0QRqh4dg/Jw1FXqtYqoENqaJyg=,tag:GLWZUfD0mKc3HXF7UC3YMg==,type:str]
    jdbc-url: ENC[AES256_GCM,data:6oS2Z4/WaAWAtUnvuZfCHe8IdL0G7AyT1CU0ZJfEez4L5JebsD2lZZFAiCM=,iv:6HI9SxKjcB+JlEs8bnrapD1Zcp/yvZlImFNGqOa/+U8=,tag:x2ikweccZn5/tFa1QRg1OQ==,type:str]
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNG5nY1dpNDNNY1Q0N1ha
            bFlCN1JURkFDYjAyV3ZZNWNXRWNlWWw5c0F3CkZBanZCNllJZTFrclhFTmVWK09G
            eVRQSDNzOFkzR3BPTTJ1LzZQNkhmelEKLS0tIEJzVWlXYnkxY2U4dzdwdGRLcGw0
            RndXY0JxQWtsQ3lvcHNseWxPSHV5TDQKSm/shUtNvH+YgLmoeVfgjPQc30Hn/jCw
            x0fSKKu3rRpsB7FULFzi7YZZbaGKW6WaDdO7FdmhKqSo7wPRRRQoew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T20:30:10Z"
    mac: ENC[AES256_GCM,data:PwabRvCY2aDCoHD1YyfZR9WqMigP7a9ppSIHqAFNpJdwLQ2U9oArt5LuT2XfgMJPz9pXC/b+61BxNUoMdcOfhRHLqExl1vexC0MAkd6xW0oSM2mBUsmykcZYDo0jY7+TryrBz7sO8wG3XbQoRVEOTtMHlTJl3X5EFCMGuRABeMA=,iv:iDU/s0qzAhUg7MZtDYZ1jDfFVTse5gJHMqX/LYhDZaA=,tag:aTDAMEd2oKoIt+jSE7lGKw==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.10.2
