apiVersion: v1
kind: Secret
metadata:
    name: anthropic-key
    namespace: lifeops-jd
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:uAneQT5ANB8Aw/tWRqJG6QLCaD6pWEKDyu/0JP8da93sPoA58ujBBu8PnTq9vTD+u9eRD0bU,iv:b/bzBson3f3IaYpeNXDLsPFjl6HYX8f5PcIPkH8KWb4=,tag:pTAMKTV+H3gBQp03GUoXng==,type:str]
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybEgwd3JqSEZKa1hUeEd0
            V21LT2I5ekxUSzRLTytGUW9QQmgxdmVZNVNvCjhibTc5N05UTXVWVW1ka0hibHhN
            VEZ1clQ4MUJ4czl6S21ORXpqaHVRV28KLS0tIHBqUnUrVE5CVzBGR094dVpYM1Ri
            MUVSYXI4Z243ZFRLejk3eE0xZy9vWDAKtUczNxLFZvZ4orejpZXwtER2yI2HycK9
            z/snf/yRZG93lCQnwRMQIQFq0hG6FcWQ5bWQNPLSgmvuTDGwwGY4Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T14:29:50Z"
    mac: ENC[AES256_GCM,data:3hyaNhsWKFRFG5MnZz2Hz9tE72cTgwOwvRdHAKDKgj2gyfflvBdQZNIANdBt5c74t+hqjtwr+kN0UjTEwMmXqKmjZARLfTyusFrNCL20U7KBIcXZ9vi6chG0My5wO9a7+Clqeq7PHYh+FjoP1bTtD0SAcfcRyyz+BjCfcPPnVh8=,iv:Gjs3WSh1FCplvdxte5ChVyvm2QVkaH2q2dChQcDt+2c=,tag:JUkYxTLvKTOIgzFossX/ag==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.10.2
