apiVersion: v1
kind: Secret
metadata:
    name: oauth-google
    namespace: lifeops-jd
type: Opaque
stringData:
    #ENC[AES256_GCM,data:8fvtN0XihTYiRFimFDb/D2TOSoHJ6a/yj1aI4HluYbhmuMeMB9cUNaPkicAhWneNa4uD2Cl+gGqKtlK7DzlCy3mii5SV8InG7Yo4UQFPESCEFQ==,iv:v5MF5/tmGgDf9GmHOoN4JYEIQFdn5xDUd9da05yNa20=,tag:WOhxn4Xqr2sBMSX49yS/fg==,type:comment]
    credentials.json: ENC[AES256_GCM,data:ZRpLwTbc7eExEpIm8AvKddF+gikMgB+UpgiPKNK9V+HOvGle2TWugL3fmblAEjC6Q/v7IQ8mrDy/3Xbl4PZ3E5dnQQt1SYGm0uq9cn5s/Z5o+7fJla6U93THKokvLjryJGxzEtGDtAWx0Eo1VCWK5JCZWdI9BOGASR7vP5QqD/UL5QXNclzIKmWTtakm3mumS32tJrHmPfHGTedZLe0kmoSo95fQ04julOZRsHqMtc+nCOZLLm0Vu3rjDMNREvKf5q6lDwtSlkCCzSON1sSpb9X1xZYirevToIC4m1GxcgKIDPFNTjbenFWrJeSHIGJqe9pF9ELl+bPsNVvpFsqzUz6vd9qVdAIMtq3ftREeLiSXkJkdETtndp9XXiWG/NvF0/j6O9TbKCa8fovazxsclsMMNkS50tbSdFOkQQqEcJd44b8hXo9vnh01msLjJ77GM10kqr8QpkamvLwG29gRIASDEl6w+cobLEZj6pS2kPuZnH7iGVsx/fOViJLGE8J4515VH86D9V0Qai45GqYTHMp6CN731J4y+taND7rl/X/M93kHO/EwodY=,iv:aSP45Fr+i4i+fJ2YxAWzIF7eNggGxfMqBCzerzLm2gY=,tag:A859/3q8Sw2kYbtcNeMCOQ==,type:str]
    token.json: ENC[AES256_GCM,data:Ul76q9a6jL+Qj+ETR/Xom+aobIp756Nv9IJ5gGGNmxIVlEbDJ4xFubcTbiBaKMCfkURN3iHII/BvGDGEsXuFwPgS2YHgLbBSJ+zR5eVyfQQT0ZxqqKt6Og29VBqLP5L7M2I43FUZtZZBeAc5atjGBOE9HCOnrq3eYIgLHtTVeHIYDLjvyb/anAAaP4aD0Ms/YkZKIK2xCLB/RYehk3uEiroRLKSP1+3MjK+FYGLz+ByNTahOyklliPPj6maG4kn3ub9Be6c+d0xYi4PBkusnlpYWSnDIBDdJKDoojEo4wO6/4RLx26nUs2rVVgLJqt59KOKC7xS19dInHMDd/bpg7GFZ4r4Cqzwu7AAfNiOzg5R3fXhGLROKTRn5kZ3/n7cWAlE=,iv:vU2ALQKgSvpqFSN5pFV+jt89MZlhZFg2ca0Mk49c+z8=,tag:UHy7yyU/X9Dnq4xx3BOdVA==,type:str]
sops:
    age:
        - recipient: age1pawume2qrtjj7zdypddpx26gn329c4k5tz7e22dh4kavmk590svs70rmp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VXhCYjJERFUyRVdmMkpR
            dWtHSmRUaUxMQ0JWczVjUFZTNDRxbHNPQ2c0CnBkUkJZSkVrS2YvNytuVHEzUVhN
            aWZuNjdiT1BlM2VhUThTQ3pLZWhLNjQKLS0tIHpQSDhDTHZlK1JZRTN2aU1jdGNq
            TjNUNzJkcVYzem1WMVVkMHkyTlJYVjQKd5Ly2erXP5p5HfEpVarUoIkYSmsQap8V
            J33ZuleCnrb249AxC8UkER8UzNgSy22xkCoeqX5X5tPI2+EoWy32og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T14:29:50Z"
    mac: ENC[AES256_GCM,data:sZ4RXqvlmcL/Hc6I/MhcsC47a8VQ2ZTga+Gef/JOLEnPm5ZrPEmNFxelw/5+9qOQAp9hZvA+9xgLJ6wusHhd9mltStacZkIbu39hK/N+yVU1Byeots5D0dgf1LMbLULBzjcpNB5/H6EohSB9/ZKS8yk+aL0IAP4fqYZTOanZxXI=,iv:jAy3ewztd8CGk8gRfrpYD1SqefZz4yAnP/tLqWgLoNw=,tag:klEpZHkGMQFVkiY9RYdvPw==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.10.2
