# SearXNG Secret Key (SOPS-encrypted)
apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:hvEhUsJI8leM6q2/GCnUxKOpDZW+QzPkB50SyZ2eJWXpkMSjq81XLbw2cZEX0/zmpXNHjrEp1F31YFqj3WBlEw==,iv:YMDsN6BIZD9nuGqTQ/JvI39xGI8O1AKn4Z8PFwy2XyY=,tag:TNJIL+IIE8Axs+cgJRlMlA==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d0JuTWlFUndZUFR0UDc0
            cEVxazdNQWtPQWl3WnFGR0pYQlcrZEJnL0c0Ck9Idlo3dUxmWTFYdGtkMVMrOThk
            VkVaeHNoRE0wckFxb1MyaEhWelR5dHcKLS0tIFpHOHlCenZaSlZReCtBeGcyYVVj
            V28xRjkyVGI1QnQzT1ZmZzdJZ3U2aG8KuNTxiSgwwHmfX+u1bt1Mzy6/x6BUxmrg
            EO5LNbpe7VMiALzPXBZlGPVDjpPLxj1r8ethdua2ps1ObZgV27X4pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T23:46:43Z"
    mac: ENC[AES256_GCM,data:7M25B7QLZMmHqEW4xD93yR+uVruGQreiD/ul+6WG5FdK1kNrX/kkuU0hdN4dmNbtZ+phpgrUUQUXjf4WNzpOz8fJmcip3DRxJpNSLaT3ZirwFpicqhLTLzCQLGHqWfAtj+WfrYI0EDE5dKDaXfCh8fKgW0/YiF6V8R9JnX2DAHc=,iv:OppKAYMDVTt92hKR4TndYPnE1NF4odgQXwzkNIyfJWA=,tag:iduuAMqYFRS5iUexAzoN9A==,type:str]
    encrypted_regex: ^(data|stringData|ssh_public_key|k3s_token|tailscale_auth_key|tailscale_api_key)$
    version: 3.12.2
