# SearXNG Secret Key (SOPS-encrypted)
apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:Li4GeWkcbD4oiz6qC8FpDYdLGbkxwKyTWkSh74lDStNbVwuLbGclQrYCRe4Y2EZwYmTg/Cf3O1y46H6Kd+MzqQ==,iv:UaQ45jEnuWFFnge+dgCCLdfFH9noZu2KgQC1LqFKxhQ=,tag:X63ZC8zcQk5nClI7bo4V+A==,type:str]
sops:
    age:
        - recipient: age18mumpukzfug863dw7j3w2tntfd6y8nf34hzx07u2fep633mprqmqc3myja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsckQ4MjlEbzRUazExV3lJ
            cjVSZDNzOXVNU1ArTi80enc1YXJjVndhL2xFCkFnQmwxWENzZEl0VjNvbGQ4aWJi
            bzgzenF1TFo1KytRSHZLbkdneUVsL1kKLS0tIGhRRndlT1J3QUFENW1Hc1Bxd3B2
            US9JZUhFaEYyY3Z0K1R0dm8rUjdsU3cKw2omUmsTbcqd6H2EXx2gurFTiAXHGHjc
            XEM5bJlDTXWSQygxh5qL8U9OTeXNU9/rgu2EOG/0AKKF/chu01KzWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T18:17:40Z"
    mac: ENC[AES256_GCM,data:CxBNBM/o7gq8TVCfzZmDuknSV8OmtkrWE9+397tufcpThrJ0FjiFym5azkCCTQHPtck4UTc+OS1/5ko+LIBLCC8DrxHcMN1x+mn1qIhf4WWDtKQ4UiwZob13Asrpqz4K2/kHIKnBFmm3yAAgbbnaRq9Sjt/wMEMB3Rk8dY6BESI=,iv:S967Yca7AQQpjqPormMrAMbDSZYc+uTJF3Gn57EpkW4=,tag:WTeiiuWf8TYCdhC5Xv1jag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
