apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
      - name: Loki
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        orgId: 1
        url: http://prometheus.prometheus.svc.cluster.local:9090
        access: proxy
        isDefault: true
        editable: true
        version: 1
      
      - name: Loki
        type: loki
        uid: loki
        orgId: 1
        url: http://loki.loki.svc.cluster.local:3100
        access: proxy
        isDefault: false
        editable: true
        version: 1
